version: 3.8
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:

    depends_on:
      - db

  db:
    image: mysql:8.1
    container_name: mysql
    ports:
      - 8083:8083
    environment:

    volumes:
      - volume:
    depends_on:
      -