pipeline{
stages{
 stage('checkout'){
    steps{
      git branch: 'master', url: ''
    }
 }
 stage('build'){
 steps{
    sh 'chmod +x mvnw'
    sh './mvnw clean package'
 }
 }
 stage('test'){
    steps{
        sh 'chmod +x mvnw'
        sh './mvnw clean test'
    }
 }
 stage('deploy'){
    steps{
        sshagent(credentails([])){
         sh '''

         '''
        }
    }
 }
}

}